spring.application.name=projeto_so

# Database - USE ESTAS CREDENCIAIS SIMPLES
spring.datasource.url=jdbc:mysql://localhost:3306/rede_mais_social
spring.datasource.username=root
spring.datasource.password=COLOQUE A SENHA DO SEU BANCO AQUI

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Server
server.port=8080

# Para evitar erro de timezone
# spring.datasource.url=jdbc:mysql://localhost:3306/rede_mais_social?useSSL=false&serverTimezone=UTC

